---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-one
spec:
  selector:
    matchLabels:
      app: client-one
  replicas: 1
  template:
    metadata:
      labels:
        app: client-one
    spec:
      containers:
      - name: client-one
        image: public.ecr.aws/docker/library/nginx:stable
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-two
spec:
  selector:
    matchLabels:
      app: client-two
  replicas: 1
  template:
    metadata:
      labels:
        app: client-two
    spec:
      containers:
      - name: client-two
        image: public.ecr.aws/docker/library/nginx:stable
        imagePullPolicy: IfNotPresent
